using System.Windows.Forms;

namespace MovieMunch
{
    partial class RegisterForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(RegisterForm));
            Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges();
            this.signUpContainer = new Bunifu.UI.WinForms.BunifuPanel();
            this.regCloseBtn = new Bunifu.UI.WinForms.BunifuFormCaptionButton();
            this.numberInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ageInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nameInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.regConfirmPasswordInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label1 = new System.Windows.Forms.Label();
            this.LoginBtnLabel = new System.Windows.Forms.LinkLabel();
            this.RegisterBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.regPasswordInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.regEmailInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuFormCaptionButton2 = new Bunifu.UI.WinForms.BunifuFormCaptionButton();
            this.signUpContainer.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // signUpContainer
            // 
            this.signUpContainer.BackgroundColor = System.Drawing.Color.White;
            this.signUpContainer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("signUpContainer.BackgroundImage")));
            this.signUpContainer.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.signUpContainer.BorderColor = System.Drawing.Color.Transparent;
            this.signUpContainer.BorderRadius = 30;
            this.signUpContainer.BorderThickness = 1;
            this.signUpContainer.Controls.Add(this.regCloseBtn);
            this.signUpContainer.Controls.Add(this.numberInput);
            this.signUpContainer.Controls.Add(this.ageInput);
            this.signUpContainer.Controls.Add(this.nameInput);
            this.signUpContainer.Controls.Add(this.regConfirmPasswordInput);
            this.signUpContainer.Controls.Add(this.pictureBox1);
            this.signUpContainer.Controls.Add(this.label1);
            this.signUpContainer.Controls.Add(this.LoginBtnLabel);
            this.signUpContainer.Controls.Add(this.RegisterBtn);
            this.signUpContainer.Controls.Add(this.regPasswordInput);
            this.signUpContainer.Controls.Add(this.regEmailInput);
            this.signUpContainer.Controls.Add(this.bunifuFormCaptionButton2);
            this.signUpContainer.Location = new System.Drawing.Point(431, 42);
            this.signUpContainer.Name = "signUpContainer";
            this.signUpContainer.ShowBorders = true;
            this.signUpContainer.Size = new System.Drawing.Size(480, 603);
            this.signUpContainer.TabIndex = 6;
            // 
            // regCloseBtn
            // 
            this.regCloseBtn.AllowAnimations = true;
            this.regCloseBtn.AllowBorderColorChanges = true;
            this.regCloseBtn.AllowDefaults = true;
            this.regCloseBtn.AllowMouseEffects = true;
            this.regCloseBtn.AnimationSpeed = 200;
            this.regCloseBtn.AutoSizeCaptions = true;
            this.regCloseBtn.BackColor = System.Drawing.Color.Transparent;
            this.regCloseBtn.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(233)))), ((int)(((byte)(233)))), ((int)(((byte)(233)))));
            this.regCloseBtn.BackHoverColor = System.Drawing.Color.LightGray;
            this.regCloseBtn.BackPressedColor = System.Drawing.Color.Silver;
            this.regCloseBtn.BorderColor = System.Drawing.Color.LightGray;
            this.regCloseBtn.BorderHoverColor = System.Drawing.Color.DarkGray;
            this.regCloseBtn.BorderPressedColor = System.Drawing.Color.DarkGray;
            this.regCloseBtn.BorderRadius = 25;
            this.regCloseBtn.BorderStyle = Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderStyles.Solid;
            this.regCloseBtn.BorderThickness = 1;
            this.regCloseBtn.CaptionType = Bunifu.UI.WinForms.BunifuFormCaptionButton.CaptionTypes.Close;
            this.regCloseBtn.ColorContrastOnClick = 30;
            this.regCloseBtn.ColorContrastOnHover = 30;
            this.regCloseBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.regCloseBtn.CustomizableEdges = borderEdges1;
            this.regCloseBtn.DefaultBorderColor = System.Drawing.Color.Silver;
            this.regCloseBtn.DefaultColor = System.Drawing.Color.Gainsboro;
            this.regCloseBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.regCloseBtn.IconColor = System.Drawing.Color.Black;
            this.regCloseBtn.IconHoverColor = System.Drawing.Color.Black;
            this.regCloseBtn.IconPressedColor = System.Drawing.Color.Black;
            this.regCloseBtn.Image = ((System.Drawing.Image)(resources.GetObject("regCloseBtn.Image")));
            this.regCloseBtn.ImageMargin = new System.Windows.Forms.Padding(1, 1, 0, 0);
            this.regCloseBtn.ImageSize = new System.Drawing.Size(20, 20);
            this.regCloseBtn.Location = new System.Drawing.Point(443, 3);
            this.regCloseBtn.Name = "regCloseBtn";
            this.regCloseBtn.ShowBorders = true;
            this.regCloseBtn.Size = new System.Drawing.Size(34, 30);
            this.regCloseBtn.TabIndex = 21;
            this.regCloseBtn.Click += new System.EventHandler(this.regCloseBtn_Click);
            // 
            // numberInput
            // 
            this.numberInput.AcceptsReturn = false;
            this.numberInput.AcceptsTab = false;
            this.numberInput.AnimationSpeed = 200;
            this.numberInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.numberInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.numberInput.AutoSizeHeight = true;
            this.numberInput.BackColor = System.Drawing.Color.Transparent;
            this.numberInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("numberInput.BackgroundImage")));
            this.numberInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.numberInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.numberInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.numberInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.numberInput.BorderRadius = 1;
            this.numberInput.BorderThickness = 1;
            this.numberInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.numberInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.numberInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.numberInput.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.numberInput.DefaultText = "";
            this.numberInput.FillColor = System.Drawing.Color.White;
            this.numberInput.ForeColor = System.Drawing.Color.Black;
            this.numberInput.HideSelection = true;
            this.numberInput.IconLeft = null;
            this.numberInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.numberInput.IconPadding = 10;
            this.numberInput.IconRight = null;
            this.numberInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.numberInput.Lines = new string[0];
            this.numberInput.Location = new System.Drawing.Point(77, 270);
            this.numberInput.MaxLength = 32767;
            this.numberInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.numberInput.Modified = false;
            this.numberInput.Multiline = false;
            this.numberInput.Name = "numberInput";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberInput.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.numberInput.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberInput.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberInput.OnIdleState = stateProperties4;
            this.numberInput.Padding = new System.Windows.Forms.Padding(3);
            this.numberInput.PasswordChar = '\0';
            this.numberInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.numberInput.PlaceholderText = "Number";
            this.numberInput.ReadOnly = false;
            this.numberInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.numberInput.SelectedText = "";
            this.numberInput.SelectionLength = 0;
            this.numberInput.SelectionStart = 0;
            this.numberInput.ShortcutsEnabled = true;
            this.numberInput.Size = new System.Drawing.Size(328, 49);
            this.numberInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.numberInput.TabIndex = 20;
            this.numberInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.numberInput.TextMarginBottom = 0;
            this.numberInput.TextMarginLeft = 3;
            this.numberInput.TextMarginTop = 1;
            this.numberInput.TextPlaceholder = "Number";
            this.numberInput.UseSystemPasswordChar = false;
            this.numberInput.WordWrap = true;
            // 
            // ageInput
            // 
            this.ageInput.AcceptsReturn = false;
            this.ageInput.AcceptsTab = false;
            this.ageInput.AnimationSpeed = 200;
            this.ageInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ageInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ageInput.AutoSizeHeight = true;
            this.ageInput.BackColor = System.Drawing.Color.Transparent;
            this.ageInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ageInput.BackgroundImage")));
            this.ageInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ageInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ageInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ageInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.ageInput.BorderRadius = 1;
            this.ageInput.BorderThickness = 1;
            this.ageInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.ageInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ageInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ageInput.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ageInput.DefaultText = "";
            this.ageInput.FillColor = System.Drawing.Color.White;
            this.ageInput.ForeColor = System.Drawing.Color.Black;
            this.ageInput.HideSelection = true;
            this.ageInput.IconLeft = null;
            this.ageInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ageInput.IconPadding = 10;
            this.ageInput.IconRight = null;
            this.ageInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ageInput.Lines = new string[0];
            this.ageInput.Location = new System.Drawing.Point(77, 215);
            this.ageInput.MaxLength = 32767;
            this.ageInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.ageInput.Modified = false;
            this.ageInput.Multiline = false;
            this.ageInput.Name = "ageInput";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageInput.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ageInput.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageInput.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageInput.OnIdleState = stateProperties8;
            this.ageInput.Padding = new System.Windows.Forms.Padding(3);
            this.ageInput.PasswordChar = '\0';
            this.ageInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ageInput.PlaceholderText = "Age";
            this.ageInput.ReadOnly = false;
            this.ageInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ageInput.SelectedText = "";
            this.ageInput.SelectionLength = 0;
            this.ageInput.SelectionStart = 0;
            this.ageInput.ShortcutsEnabled = true;
            this.ageInput.Size = new System.Drawing.Size(328, 49);
            this.ageInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ageInput.TabIndex = 19;
            this.ageInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ageInput.TextMarginBottom = 0;
            this.ageInput.TextMarginLeft = 3;
            this.ageInput.TextMarginTop = 1;
            this.ageInput.TextPlaceholder = "Age";
            this.ageInput.UseSystemPasswordChar = false;
            this.ageInput.WordWrap = true;
            // 
            // nameInput
            // 
            this.nameInput.AcceptsReturn = false;
            this.nameInput.AcceptsTab = false;
            this.nameInput.AnimationSpeed = 200;
            this.nameInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nameInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nameInput.AutoSizeHeight = true;
            this.nameInput.BackColor = System.Drawing.Color.Transparent;
            this.nameInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nameInput.BackgroundImage")));
            this.nameInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nameInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nameInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nameInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.nameInput.BorderRadius = 1;
            this.nameInput.BorderThickness = 1;
            this.nameInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.nameInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nameInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nameInput.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nameInput.DefaultText = "";
            this.nameInput.FillColor = System.Drawing.Color.White;
            this.nameInput.ForeColor = System.Drawing.Color.Black;
            this.nameInput.HideSelection = true;
            this.nameInput.IconLeft = null;
            this.nameInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameInput.IconPadding = 10;
            this.nameInput.IconRight = null;
            this.nameInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameInput.Lines = new string[0];
            this.nameInput.Location = new System.Drawing.Point(77, 160);
            this.nameInput.MaxLength = 32767;
            this.nameInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.nameInput.Modified = false;
            this.nameInput.Multiline = false;
            this.nameInput.Name = "nameInput";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameInput.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nameInput.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameInput.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameInput.OnIdleState = stateProperties12;
            this.nameInput.Padding = new System.Windows.Forms.Padding(3);
            this.nameInput.PasswordChar = '\0';
            this.nameInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nameInput.PlaceholderText = "Name";
            this.nameInput.ReadOnly = false;
            this.nameInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nameInput.SelectedText = "";
            this.nameInput.SelectionLength = 0;
            this.nameInput.SelectionStart = 0;
            this.nameInput.ShortcutsEnabled = true;
            this.nameInput.Size = new System.Drawing.Size(328, 49);
            this.nameInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nameInput.TabIndex = 18;
            this.nameInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nameInput.TextMarginBottom = 0;
            this.nameInput.TextMarginLeft = 3;
            this.nameInput.TextMarginTop = 1;
            this.nameInput.TextPlaceholder = "Name";
            this.nameInput.UseSystemPasswordChar = false;
            this.nameInput.WordWrap = true;
            // 
            // regConfirmPasswordInput
            // 
            this.regConfirmPasswordInput.AcceptsReturn = false;
            this.regConfirmPasswordInput.AcceptsTab = false;
            this.regConfirmPasswordInput.AnimationSpeed = 200;
            this.regConfirmPasswordInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.regConfirmPasswordInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.regConfirmPasswordInput.AutoSizeHeight = true;
            this.regConfirmPasswordInput.BackColor = System.Drawing.Color.Transparent;
            this.regConfirmPasswordInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("regConfirmPasswordInput.BackgroundImage")));
            this.regConfirmPasswordInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.regConfirmPasswordInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.regConfirmPasswordInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.regConfirmPasswordInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.regConfirmPasswordInput.BorderRadius = 1;
            this.regConfirmPasswordInput.BorderThickness = 1;
            this.regConfirmPasswordInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.regConfirmPasswordInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.regConfirmPasswordInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.regConfirmPasswordInput.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.regConfirmPasswordInput.DefaultText = "";
            this.regConfirmPasswordInput.FillColor = System.Drawing.Color.White;
            this.regConfirmPasswordInput.ForeColor = System.Drawing.Color.Black;
            this.regConfirmPasswordInput.HideSelection = true;
            this.regConfirmPasswordInput.IconLeft = null;
            this.regConfirmPasswordInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.regConfirmPasswordInput.IconPadding = 10;
            this.regConfirmPasswordInput.IconRight = null;
            this.regConfirmPasswordInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.regConfirmPasswordInput.Lines = new string[0];
            this.regConfirmPasswordInput.Location = new System.Drawing.Point(77, 435);
            this.regConfirmPasswordInput.MaxLength = 32767;
            this.regConfirmPasswordInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.regConfirmPasswordInput.Modified = false;
            this.regConfirmPasswordInput.Multiline = false;
            this.regConfirmPasswordInput.Name = "regConfirmPasswordInput";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regConfirmPasswordInput.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.regConfirmPasswordInput.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regConfirmPasswordInput.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regConfirmPasswordInput.OnIdleState = stateProperties16;
            this.regConfirmPasswordInput.Padding = new System.Windows.Forms.Padding(3);
            this.regConfirmPasswordInput.PasswordChar = '\0';
            this.regConfirmPasswordInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.regConfirmPasswordInput.PlaceholderText = "Confirm Password";
            this.regConfirmPasswordInput.ReadOnly = false;
            this.regConfirmPasswordInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.regConfirmPasswordInput.SelectedText = "";
            this.regConfirmPasswordInput.SelectionLength = 0;
            this.regConfirmPasswordInput.SelectionStart = 0;
            this.regConfirmPasswordInput.ShortcutsEnabled = true;
            this.regConfirmPasswordInput.Size = new System.Drawing.Size(328, 49);
            this.regConfirmPasswordInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.regConfirmPasswordInput.TabIndex = 17;
            this.regConfirmPasswordInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.regConfirmPasswordInput.TextMarginBottom = 0;
            this.regConfirmPasswordInput.TextMarginLeft = 3;
            this.regConfirmPasswordInput.TextMarginTop = 1;
            this.regConfirmPasswordInput.TextPlaceholder = "Confirm Password";
            this.regConfirmPasswordInput.UseSystemPasswordChar = true;
            this.regConfirmPasswordInput.WordWrap = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.BackgroundImage = global::MovieMunch.Properties.Resources.MovieMunchLogo_removebg_preview;
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox1.Location = new System.Drawing.Point(125, 19);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(233, 124);
            this.pictureBox1.TabIndex = 16;
            this.pictureBox1.TabStop = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.White;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Black;
            this.label1.Location = new System.Drawing.Point(95, 558);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(176, 18);
            this.label1.TabIndex = 15;
            this.label1.Text = "Already have an account?";
            // 
            // LoginBtnLabel
            // 
            this.LoginBtnLabel.AutoSize = true;
            this.LoginBtnLabel.BackColor = System.Drawing.Color.White;
            this.LoginBtnLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LoginBtnLabel.ForeColor = System.Drawing.SystemColors.ControlText;
            this.LoginBtnLabel.LinkColor = System.Drawing.Color.Black;
            this.LoginBtnLabel.Location = new System.Drawing.Point(317, 558);
            this.LoginBtnLabel.Name = "LoginBtnLabel";
            this.LoginBtnLabel.Size = new System.Drawing.Size(44, 18);
            this.LoginBtnLabel.TabIndex = 14;
            this.LoginBtnLabel.TabStop = true;
            this.LoginBtnLabel.Text = "Login";
            this.LoginBtnLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.LoginBtnLabel_LinkClicked);
            // 
            // RegisterBtn
            // 
            this.RegisterBtn.AllowAnimations = true;
            this.RegisterBtn.AllowMouseEffects = true;
            this.RegisterBtn.AllowToggling = false;
            this.RegisterBtn.AnimationSpeed = 200;
            this.RegisterBtn.AutoGenerateColors = false;
            this.RegisterBtn.AutoRoundBorders = false;
            this.RegisterBtn.AutoSizeLeftIcon = true;
            this.RegisterBtn.AutoSizeRightIcon = true;
            this.RegisterBtn.BackColor = System.Drawing.Color.Transparent;
            this.RegisterBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.RegisterBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RegisterBtn.BackgroundImage")));
            this.RegisterBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.RegisterBtn.ButtonText = "Register";
            this.RegisterBtn.ButtonTextMarginLeft = 0;
            this.RegisterBtn.ColorContrastOnClick = 45;
            this.RegisterBtn.ColorContrastOnHover = 45;
            this.RegisterBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.RegisterBtn.CustomizableEdges = borderEdges2;
            this.RegisterBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.RegisterBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegisterBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RegisterBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RegisterBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.RegisterBtn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RegisterBtn.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.RegisterBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.RegisterBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.RegisterBtn.IconMarginLeft = 11;
            this.RegisterBtn.IconPadding = 10;
            this.RegisterBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.RegisterBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.RegisterBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.RegisterBtn.IconSize = 25;
            this.RegisterBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.RegisterBtn.IdleBorderRadius = 35;
            this.RegisterBtn.IdleBorderThickness = 1;
            this.RegisterBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.RegisterBtn.IdleIconLeftImage = null;
            this.RegisterBtn.IdleIconRightImage = null;
            this.RegisterBtn.IndicateFocus = false;
            this.RegisterBtn.Location = new System.Drawing.Point(142, 493);
            this.RegisterBtn.Name = "RegisterBtn";
            this.RegisterBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegisterBtn.OnDisabledState.BorderRadius = 35;
            this.RegisterBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.RegisterBtn.OnDisabledState.BorderThickness = 1;
            this.RegisterBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RegisterBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RegisterBtn.OnDisabledState.IconLeftImage = null;
            this.RegisterBtn.OnDisabledState.IconRightImage = null;
            this.RegisterBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RegisterBtn.onHoverState.BorderRadius = 35;
            this.RegisterBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.RegisterBtn.onHoverState.BorderThickness = 1;
            this.RegisterBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RegisterBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.onHoverState.IconLeftImage = null;
            this.RegisterBtn.onHoverState.IconRightImage = null;
            this.RegisterBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.RegisterBtn.OnIdleState.BorderRadius = 35;
            this.RegisterBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.RegisterBtn.OnIdleState.BorderThickness = 1;
            this.RegisterBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.RegisterBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.OnIdleState.IconLeftImage = null;
            this.RegisterBtn.OnIdleState.IconRightImage = null;
            this.RegisterBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RegisterBtn.OnPressedState.BorderRadius = 35;
            this.RegisterBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.RegisterBtn.OnPressedState.BorderThickness = 1;
            this.RegisterBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RegisterBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.OnPressedState.IconLeftImage = null;
            this.RegisterBtn.OnPressedState.IconRightImage = null;
            this.RegisterBtn.Size = new System.Drawing.Size(201, 39);
            this.RegisterBtn.TabIndex = 13;
            this.RegisterBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.RegisterBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.RegisterBtn.TextMarginLeft = 0;
            this.RegisterBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.RegisterBtn.UseDefaultRadiusAndThickness = true;
            this.RegisterBtn.Click += new System.EventHandler(this.RegisterBtn_Click);
            // 
            // regPasswordInput
            // 
            this.regPasswordInput.AcceptsReturn = false;
            this.regPasswordInput.AcceptsTab = false;
            this.regPasswordInput.AnimationSpeed = 200;
            this.regPasswordInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.regPasswordInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.regPasswordInput.AutoSizeHeight = true;
            this.regPasswordInput.BackColor = System.Drawing.Color.Transparent;
            this.regPasswordInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("regPasswordInput.BackgroundImage")));
            this.regPasswordInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.regPasswordInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.regPasswordInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.regPasswordInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.regPasswordInput.BorderRadius = 1;
            this.regPasswordInput.BorderThickness = 1;
            this.regPasswordInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.regPasswordInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.regPasswordInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.regPasswordInput.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.regPasswordInput.DefaultText = "";
            this.regPasswordInput.FillColor = System.Drawing.Color.White;
            this.regPasswordInput.ForeColor = System.Drawing.Color.Black;
            this.regPasswordInput.HideSelection = true;
            this.regPasswordInput.IconLeft = null;
            this.regPasswordInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.regPasswordInput.IconPadding = 10;
            this.regPasswordInput.IconRight = null;
            this.regPasswordInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.regPasswordInput.Lines = new string[0];
            this.regPasswordInput.Location = new System.Drawing.Point(77, 380);
            this.regPasswordInput.MaxLength = 32767;
            this.regPasswordInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.regPasswordInput.Modified = false;
            this.regPasswordInput.Multiline = false;
            this.regPasswordInput.Name = "regPasswordInput";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regPasswordInput.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.regPasswordInput.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regPasswordInput.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regPasswordInput.OnIdleState = stateProperties20;
            this.regPasswordInput.Padding = new System.Windows.Forms.Padding(3);
            this.regPasswordInput.PasswordChar = '\0';
            this.regPasswordInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.regPasswordInput.PlaceholderText = "Password";
            this.regPasswordInput.ReadOnly = false;
            this.regPasswordInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.regPasswordInput.SelectedText = "";
            this.regPasswordInput.SelectionLength = 0;
            this.regPasswordInput.SelectionStart = 0;
            this.regPasswordInput.ShortcutsEnabled = true;
            this.regPasswordInput.Size = new System.Drawing.Size(328, 49);
            this.regPasswordInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.regPasswordInput.TabIndex = 12;
            this.regPasswordInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.regPasswordInput.TextMarginBottom = 0;
            this.regPasswordInput.TextMarginLeft = 3;
            this.regPasswordInput.TextMarginTop = 1;
            this.regPasswordInput.TextPlaceholder = "Password";
            this.regPasswordInput.UseSystemPasswordChar = true;
            this.regPasswordInput.WordWrap = true;
            // 
            // regEmailInput
            // 
            this.regEmailInput.AcceptsReturn = false;
            this.regEmailInput.AcceptsTab = false;
            this.regEmailInput.AnimationSpeed = 200;
            this.regEmailInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.regEmailInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.regEmailInput.AutoSizeHeight = true;
            this.regEmailInput.BackColor = System.Drawing.Color.Transparent;
            this.regEmailInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("regEmailInput.BackgroundImage")));
            this.regEmailInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.regEmailInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.regEmailInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.regEmailInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.regEmailInput.BorderRadius = 1;
            this.regEmailInput.BorderThickness = 1;
            this.regEmailInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.regEmailInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.regEmailInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.regEmailInput.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.regEmailInput.DefaultText = "";
            this.regEmailInput.FillColor = System.Drawing.Color.White;
            this.regEmailInput.ForeColor = System.Drawing.Color.Black;
            this.regEmailInput.HideSelection = true;
            this.regEmailInput.IconLeft = null;
            this.regEmailInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.regEmailInput.IconPadding = 10;
            this.regEmailInput.IconRight = null;
            this.regEmailInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.regEmailInput.Lines = new string[0];
            this.regEmailInput.Location = new System.Drawing.Point(77, 325);
            this.regEmailInput.MaxLength = 32767;
            this.regEmailInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.regEmailInput.Modified = false;
            this.regEmailInput.Multiline = false;
            this.regEmailInput.Name = "regEmailInput";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regEmailInput.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.regEmailInput.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regEmailInput.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regEmailInput.OnIdleState = stateProperties24;
            this.regEmailInput.Padding = new System.Windows.Forms.Padding(3);
            this.regEmailInput.PasswordChar = '\0';
            this.regEmailInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.regEmailInput.PlaceholderText = "Email";
            this.regEmailInput.ReadOnly = false;
            this.regEmailInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.regEmailInput.SelectedText = "";
            this.regEmailInput.SelectionLength = 0;
            this.regEmailInput.SelectionStart = 0;
            this.regEmailInput.ShortcutsEnabled = true;
            this.regEmailInput.Size = new System.Drawing.Size(328, 49);
            this.regEmailInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.regEmailInput.TabIndex = 11;
            this.regEmailInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.regEmailInput.TextMarginBottom = 0;
            this.regEmailInput.TextMarginLeft = 3;
            this.regEmailInput.TextMarginTop = 1;
            this.regEmailInput.TextPlaceholder = "Email";
            this.regEmailInput.UseSystemPasswordChar = false;
            this.regEmailInput.WordWrap = true;
            // 
            // bunifuFormCaptionButton2
            // 
            this.bunifuFormCaptionButton2.AllowAnimations = true;
            this.bunifuFormCaptionButton2.AllowBorderColorChanges = true;
            this.bunifuFormCaptionButton2.AllowDefaults = true;
            this.bunifuFormCaptionButton2.AllowMouseEffects = true;
            this.bunifuFormCaptionButton2.AnimationSpeed = 200;
            this.bunifuFormCaptionButton2.AutoSizeCaptions = true;
            this.bunifuFormCaptionButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormCaptionButton2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(233)))), ((int)(((byte)(233)))), ((int)(((byte)(233)))));
            this.bunifuFormCaptionButton2.BackHoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormCaptionButton2.BackPressedColor = System.Drawing.Color.Silver;
            this.bunifuFormCaptionButton2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuFormCaptionButton2.BorderHoverColor = System.Drawing.Color.DarkGray;
            this.bunifuFormCaptionButton2.BorderPressedColor = System.Drawing.Color.DarkGray;
            this.bunifuFormCaptionButton2.BorderRadius = 25;
            this.bunifuFormCaptionButton2.BorderStyle = Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderStyles.Solid;
            this.bunifuFormCaptionButton2.BorderThickness = 1;
            this.bunifuFormCaptionButton2.CaptionType = Bunifu.UI.WinForms.BunifuFormCaptionButton.CaptionTypes.Close;
            this.bunifuFormCaptionButton2.ColorContrastOnClick = 30;
            this.bunifuFormCaptionButton2.ColorContrastOnHover = 30;
            this.bunifuFormCaptionButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuFormCaptionButton2.CustomizableEdges = borderEdges3;
            this.bunifuFormCaptionButton2.DefaultBorderColor = System.Drawing.Color.Silver;
            this.bunifuFormCaptionButton2.DefaultColor = System.Drawing.Color.Gainsboro;
            this.bunifuFormCaptionButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuFormCaptionButton2.IconColor = System.Drawing.Color.Black;
            this.bunifuFormCaptionButton2.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormCaptionButton2.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormCaptionButton2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuFormCaptionButton2.Image")));
            this.bunifuFormCaptionButton2.ImageMargin = new System.Windows.Forms.Padding(1, 1, 0, 0);
            this.bunifuFormCaptionButton2.ImageSize = new System.Drawing.Size(20, 20);
            this.bunifuFormCaptionButton2.Location = new System.Drawing.Point(783, 3);
            this.bunifuFormCaptionButton2.Name = "bunifuFormCaptionButton2";
            this.bunifuFormCaptionButton2.ShowBorders = true;
            this.bunifuFormCaptionButton2.Size = new System.Drawing.Size(34, 30);
            this.bunifuFormCaptionButton2.TabIndex = 3;
            // 
            // RegisterForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(20)))), ((int)(((byte)(44)))));
            this.ClientSize = new System.Drawing.Size(1343, 687);
            this.Controls.Add(this.signUpContainer);
            this.ForeColor = System.Drawing.Color.White;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "RegisterForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Register Form";
            this.signUpContainer.ResumeLayout(false);
            this.signUpContainer.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel signUpContainer;
        private Bunifu.UI.WinForms.BunifuTextBox numberInput;
        private Bunifu.UI.WinForms.BunifuTextBox ageInput;
        private Bunifu.UI.WinForms.BunifuTextBox nameInput;
        private Bunifu.UI.WinForms.BunifuTextBox regConfirmPasswordInput;
        private PictureBox pictureBox1;
        private Label label1;
        private LinkLabel LoginBtnLabel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 RegisterBtn;
        private Bunifu.UI.WinForms.BunifuTextBox regPasswordInput;
        private Bunifu.UI.WinForms.BunifuTextBox regEmailInput;
        private Bunifu.UI.WinForms.BunifuFormCaptionButton bunifuFormCaptionButton2;
        private Bunifu.UI.WinForms.BunifuFormCaptionButton regCloseBtn;
    }
}
