using System.Windows.Forms;

namespace MovieMunch
{
    partial class RegisterForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(RegisterForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges();
            this.signUpContainer = new Bunifu.UI.WinForms.BunifuPanel();
            this.label4 = new System.Windows.Forms.Label();
            this.bunifuButton24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.linkLabel2 = new System.Windows.Forms.LinkLabel();
            this.linkLabel1 = new System.Windows.Forms.LinkLabel();
            this.label3 = new System.Windows.Forms.Label();
            this.regConfirmPasswordInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.regEmailInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.regPasswordInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.regNumberInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.regCloseBtn = new Bunifu.UI.WinForms.BunifuFormCaptionButton();
            this.regAgeInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.regNameInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.LoginBtnLabel = new System.Windows.Forms.LinkLabel();
            this.RegisterBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuFormCaptionButton2 = new Bunifu.UI.WinForms.BunifuFormCaptionButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label5 = new System.Windows.Forms.Label();
            this.signUpContainer.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // signUpContainer
            // 
            this.signUpContainer.BackgroundColor = System.Drawing.Color.White;
            this.signUpContainer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("signUpContainer.BackgroundImage")));
            this.signUpContainer.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.signUpContainer.BorderColor = System.Drawing.Color.Transparent;
            this.signUpContainer.BorderRadius = 30;
            this.signUpContainer.BorderThickness = 1;
            this.signUpContainer.Controls.Add(this.label4);
            this.signUpContainer.Controls.Add(this.bunifuButton24);
            this.signUpContainer.Controls.Add(this.bunifuButton22);
            this.signUpContainer.Controls.Add(this.bunifuButton21);
            this.signUpContainer.Controls.Add(this.linkLabel2);
            this.signUpContainer.Controls.Add(this.linkLabel1);
            this.signUpContainer.Controls.Add(this.label3);
            this.signUpContainer.Controls.Add(this.regConfirmPasswordInput);
            this.signUpContainer.Controls.Add(this.regEmailInput);
            this.signUpContainer.Controls.Add(this.regPasswordInput);
            this.signUpContainer.Controls.Add(this.regNumberInput);
            this.signUpContainer.Controls.Add(this.label2);
            this.signUpContainer.Controls.Add(this.label7);
            this.signUpContainer.Controls.Add(this.regCloseBtn);
            this.signUpContainer.Controls.Add(this.regAgeInput);
            this.signUpContainer.Controls.Add(this.regNameInput);
            this.signUpContainer.Controls.Add(this.label1);
            this.signUpContainer.Controls.Add(this.LoginBtnLabel);
            this.signUpContainer.Controls.Add(this.RegisterBtn);
            this.signUpContainer.Controls.Add(this.bunifuFormCaptionButton2);
            this.signUpContainer.Location = new System.Drawing.Point(708, 10);
            this.signUpContainer.Name = "signUpContainer";
            this.signUpContainer.ShowBorders = true;
            this.signUpContainer.Size = new System.Drawing.Size(480, 628);
            this.signUpContainer.TabIndex = 6;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.White;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.Gray;
            this.label4.Location = new System.Drawing.Point(216, 202);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(51, 29);
            this.label4.TabIndex = 33;
            this.label4.Text = "OR";
            // 
            // bunifuButton24
            // 
            this.bunifuButton24.AllowAnimations = true;
            this.bunifuButton24.AllowMouseEffects = true;
            this.bunifuButton24.AllowToggling = false;
            this.bunifuButton24.AnimationSpeed = 200;
            this.bunifuButton24.AutoGenerateColors = false;
            this.bunifuButton24.AutoRoundBorders = false;
            this.bunifuButton24.AutoSizeLeftIcon = true;
            this.bunifuButton24.AutoSizeRightIcon = true;
            this.bunifuButton24.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton24.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton24.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton24.BackgroundImage")));
            this.bunifuButton24.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton24.ButtonText = "Facebook";
            this.bunifuButton24.ButtonTextMarginLeft = 0;
            this.bunifuButton24.ColorContrastOnClick = 45;
            this.bunifuButton24.ColorContrastOnHover = 45;
            this.bunifuButton24.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton24.CustomizableEdges = borderEdges1;
            this.bunifuButton24.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton24.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton24.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton24.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton24.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton24.Font = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton24.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton24.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton24.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton24.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton24.IconMarginLeft = 11;
            this.bunifuButton24.IconPadding = 10;
            this.bunifuButton24.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton24.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton24.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton24.IconSize = 25;
            this.bunifuButton24.IdleBorderColor = System.Drawing.Color.Gray;
            this.bunifuButton24.IdleBorderRadius = 20;
            this.bunifuButton24.IdleBorderThickness = 1;
            this.bunifuButton24.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton24.IdleIconLeftImage = null;
            this.bunifuButton24.IdleIconRightImage = null;
            this.bunifuButton24.IndicateFocus = false;
            this.bunifuButton24.Location = new System.Drawing.Point(245, 81);
            this.bunifuButton24.Name = "bunifuButton24";
            this.bunifuButton24.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton24.OnDisabledState.BorderRadius = 20;
            this.bunifuButton24.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton24.OnDisabledState.BorderThickness = 1;
            this.bunifuButton24.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton24.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton24.OnDisabledState.IconLeftImage = null;
            this.bunifuButton24.OnDisabledState.IconRightImage = null;
            this.bunifuButton24.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton24.onHoverState.BorderRadius = 20;
            this.bunifuButton24.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton24.onHoverState.BorderThickness = 1;
            this.bunifuButton24.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton24.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton24.onHoverState.IconLeftImage = null;
            this.bunifuButton24.onHoverState.IconRightImage = null;
            this.bunifuButton24.OnIdleState.BorderColor = System.Drawing.Color.Gray;
            this.bunifuButton24.OnIdleState.BorderRadius = 20;
            this.bunifuButton24.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton24.OnIdleState.BorderThickness = 1;
            this.bunifuButton24.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton24.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton24.OnIdleState.IconLeftImage = null;
            this.bunifuButton24.OnIdleState.IconRightImage = null;
            this.bunifuButton24.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton24.OnPressedState.BorderRadius = 20;
            this.bunifuButton24.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton24.OnPressedState.BorderThickness = 1;
            this.bunifuButton24.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton24.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton24.OnPressedState.IconLeftImage = null;
            this.bunifuButton24.OnPressedState.IconRightImage = null;
            this.bunifuButton24.Size = new System.Drawing.Size(187, 51);
            this.bunifuButton24.TabIndex = 31;
            this.bunifuButton24.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton24.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton24.TextMarginLeft = 0;
            this.bunifuButton24.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.bunifuButton24.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = false;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = false;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "Github";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges2;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton22.Font = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton22.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 10;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 25;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.Gray;
            this.bunifuButton22.IdleBorderRadius = 20;
            this.bunifuButton22.IdleBorderThickness = 1;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton22.IdleIconLeftImage = null;
            this.bunifuButton22.IdleIconRightImage = null;
            this.bunifuButton22.IndicateFocus = false;
            this.bunifuButton22.Location = new System.Drawing.Point(46, 138);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.OnDisabledState.BorderRadius = 20;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 1;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.BorderRadius = 20;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 1;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.Gray;
            this.bunifuButton22.OnIdleState.BorderRadius = 20;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 1;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton22.OnIdleState.IconLeftImage = null;
            this.bunifuButton22.OnIdleState.IconRightImage = null;
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.BorderRadius = 20;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 1;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new System.Drawing.Size(187, 51);
            this.bunifuButton22.TabIndex = 30;
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Google";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges3;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.Gray;
            this.bunifuButton21.IdleBorderRadius = 20;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(46, 81);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 20;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.BorderRadius = 20;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.Gray;
            this.bunifuButton21.OnIdleState.BorderRadius = 20;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 20;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(187, 51);
            this.bunifuButton21.TabIndex = 29;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            // 
            // linkLabel2
            // 
            this.linkLabel2.AutoSize = true;
            this.linkLabel2.BackColor = System.Drawing.Color.White;
            this.linkLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.linkLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.linkLabel2.LinkColor = System.Drawing.Color.BlueViolet;
            this.linkLabel2.Location = new System.Drawing.Point(227, 601);
            this.linkLabel2.Name = "linkLabel2";
            this.linkLabel2.Size = new System.Drawing.Size(95, 16);
            this.linkLabel2.TabIndex = 28;
            this.linkLabel2.TabStop = true;
            this.linkLabel2.Text = "Privacy Policy.";
            // 
            // linkLabel1
            // 
            this.linkLabel1.AutoSize = true;
            this.linkLabel1.BackColor = System.Drawing.Color.White;
            this.linkLabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.linkLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.linkLabel1.LinkColor = System.Drawing.Color.BlueViolet;
            this.linkLabel1.Location = new System.Drawing.Point(283, 573);
            this.linkLabel1.Name = "linkLabel1";
            this.linkLabel1.Size = new System.Drawing.Size(120, 16);
            this.linkLabel1.TabIndex = 27;
            this.linkLabel1.TabStop = true;
            this.linkLabel1.Text = "Terms and Privacy";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.White;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.Black;
            this.label3.Location = new System.Drawing.Point(191, 601);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(30, 16);
            this.label3.TabIndex = 26;
            this.label3.Text = "and";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // regConfirmPasswordInput
            // 
            this.regConfirmPasswordInput.AcceptsReturn = false;
            this.regConfirmPasswordInput.AcceptsTab = false;
            this.regConfirmPasswordInput.AnimationSpeed = 200;
            this.regConfirmPasswordInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.regConfirmPasswordInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.regConfirmPasswordInput.AutoSizeHeight = true;
            this.regConfirmPasswordInput.BackColor = System.Drawing.Color.Transparent;
            this.regConfirmPasswordInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("regConfirmPasswordInput.BackgroundImage")));
            this.regConfirmPasswordInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.regConfirmPasswordInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.regConfirmPasswordInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.regConfirmPasswordInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.regConfirmPasswordInput.BorderRadius = 20;
            this.regConfirmPasswordInput.BorderThickness = 1;
            this.regConfirmPasswordInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.regConfirmPasswordInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.regConfirmPasswordInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.regConfirmPasswordInput.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.regConfirmPasswordInput.DefaultText = "";
            this.regConfirmPasswordInput.FillColor = System.Drawing.Color.White;
            this.regConfirmPasswordInput.ForeColor = System.Drawing.Color.Black;
            this.regConfirmPasswordInput.HideSelection = true;
            this.regConfirmPasswordInput.IconLeft = null;
            this.regConfirmPasswordInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.regConfirmPasswordInput.IconPadding = 10;
            this.regConfirmPasswordInput.IconRight = null;
            this.regConfirmPasswordInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.regConfirmPasswordInput.Lines = new string[0];
            this.regConfirmPasswordInput.Location = new System.Drawing.Point(46, 466);
            this.regConfirmPasswordInput.MaxLength = 32767;
            this.regConfirmPasswordInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.regConfirmPasswordInput.Modified = false;
            this.regConfirmPasswordInput.Multiline = false;
            this.regConfirmPasswordInput.Name = "regConfirmPasswordInput";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regConfirmPasswordInput.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.regConfirmPasswordInput.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regConfirmPasswordInput.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regConfirmPasswordInput.OnIdleState = stateProperties4;
            this.regConfirmPasswordInput.Padding = new System.Windows.Forms.Padding(3);
            this.regConfirmPasswordInput.PasswordChar = '\0';
            this.regConfirmPasswordInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.regConfirmPasswordInput.PlaceholderText = "Confirm password";
            this.regConfirmPasswordInput.ReadOnly = false;
            this.regConfirmPasswordInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.regConfirmPasswordInput.SelectedText = "";
            this.regConfirmPasswordInput.SelectionLength = 0;
            this.regConfirmPasswordInput.SelectionStart = 0;
            this.regConfirmPasswordInput.ShortcutsEnabled = true;
            this.regConfirmPasswordInput.Size = new System.Drawing.Size(386, 45);
            this.regConfirmPasswordInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.regConfirmPasswordInput.TabIndex = 21;
            this.regConfirmPasswordInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.regConfirmPasswordInput.TextMarginBottom = 0;
            this.regConfirmPasswordInput.TextMarginLeft = 3;
            this.regConfirmPasswordInput.TextMarginTop = 1;
            this.regConfirmPasswordInput.TextPlaceholder = "Confirm password";
            this.regConfirmPasswordInput.UseSystemPasswordChar = true;
            this.regConfirmPasswordInput.WordWrap = true;
            // 
            // regEmailInput
            // 
            this.regEmailInput.AcceptsReturn = false;
            this.regEmailInput.AcceptsTab = false;
            this.regEmailInput.AnimationSpeed = 200;
            this.regEmailInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.regEmailInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.regEmailInput.AutoSizeHeight = true;
            this.regEmailInput.BackColor = System.Drawing.Color.Transparent;
            this.regEmailInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("regEmailInput.BackgroundImage")));
            this.regEmailInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.regEmailInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.regEmailInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.regEmailInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.regEmailInput.BorderRadius = 20;
            this.regEmailInput.BorderThickness = 1;
            this.regEmailInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.regEmailInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.regEmailInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.regEmailInput.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.regEmailInput.DefaultText = "";
            this.regEmailInput.FillColor = System.Drawing.Color.White;
            this.regEmailInput.ForeColor = System.Drawing.Color.Black;
            this.regEmailInput.HideSelection = true;
            this.regEmailInput.IconLeft = null;
            this.regEmailInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.regEmailInput.IconPadding = 10;
            this.regEmailInput.IconRight = null;
            this.regEmailInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.regEmailInput.Lines = new string[0];
            this.regEmailInput.Location = new System.Drawing.Point(46, 373);
            this.regEmailInput.MaxLength = 32767;
            this.regEmailInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.regEmailInput.Modified = false;
            this.regEmailInput.Multiline = false;
            this.regEmailInput.Name = "regEmailInput";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regEmailInput.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.regEmailInput.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regEmailInput.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regEmailInput.OnIdleState = stateProperties8;
            this.regEmailInput.Padding = new System.Windows.Forms.Padding(3);
            this.regEmailInput.PasswordChar = '\0';
            this.regEmailInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.regEmailInput.PlaceholderText = "Email";
            this.regEmailInput.ReadOnly = false;
            this.regEmailInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.regEmailInput.SelectedText = "";
            this.regEmailInput.SelectionLength = 0;
            this.regEmailInput.SelectionStart = 0;
            this.regEmailInput.ShortcutsEnabled = true;
            this.regEmailInput.Size = new System.Drawing.Size(386, 45);
            this.regEmailInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.regEmailInput.TabIndex = 25;
            this.regEmailInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.regEmailInput.TextMarginBottom = 0;
            this.regEmailInput.TextMarginLeft = 3;
            this.regEmailInput.TextMarginTop = 1;
            this.regEmailInput.TextPlaceholder = "Email";
            this.regEmailInput.UseSystemPasswordChar = false;
            this.regEmailInput.WordWrap = true;
            // 
            // regPasswordInput
            // 
            this.regPasswordInput.AcceptsReturn = false;
            this.regPasswordInput.AcceptsTab = false;
            this.regPasswordInput.AnimationSpeed = 200;
            this.regPasswordInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.regPasswordInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.regPasswordInput.AutoSizeHeight = true;
            this.regPasswordInput.BackColor = System.Drawing.Color.Transparent;
            this.regPasswordInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("regPasswordInput.BackgroundImage")));
            this.regPasswordInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.regPasswordInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.regPasswordInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.regPasswordInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.regPasswordInput.BorderRadius = 20;
            this.regPasswordInput.BorderThickness = 1;
            this.regPasswordInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.regPasswordInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.regPasswordInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.regPasswordInput.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.regPasswordInput.DefaultText = "";
            this.regPasswordInput.FillColor = System.Drawing.Color.White;
            this.regPasswordInput.ForeColor = System.Drawing.Color.Black;
            this.regPasswordInput.HideSelection = true;
            this.regPasswordInput.IconLeft = null;
            this.regPasswordInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.regPasswordInput.IconPadding = 10;
            this.regPasswordInput.IconRight = null;
            this.regPasswordInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.regPasswordInput.Lines = new string[0];
            this.regPasswordInput.Location = new System.Drawing.Point(46, 419);
            this.regPasswordInput.MaxLength = 32767;
            this.regPasswordInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.regPasswordInput.Modified = false;
            this.regPasswordInput.Multiline = false;
            this.regPasswordInput.Name = "regPasswordInput";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regPasswordInput.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.regPasswordInput.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regPasswordInput.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regPasswordInput.OnIdleState = stateProperties12;
            this.regPasswordInput.Padding = new System.Windows.Forms.Padding(3);
            this.regPasswordInput.PasswordChar = '\0';
            this.regPasswordInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.regPasswordInput.PlaceholderText = "Password";
            this.regPasswordInput.ReadOnly = false;
            this.regPasswordInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.regPasswordInput.SelectedText = "";
            this.regPasswordInput.SelectionLength = 0;
            this.regPasswordInput.SelectionStart = 0;
            this.regPasswordInput.ShortcutsEnabled = true;
            this.regPasswordInput.Size = new System.Drawing.Size(386, 45);
            this.regPasswordInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.regPasswordInput.TabIndex = 20;
            this.regPasswordInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.regPasswordInput.TextMarginBottom = 0;
            this.regPasswordInput.TextMarginLeft = 3;
            this.regPasswordInput.TextMarginTop = 1;
            this.regPasswordInput.TextPlaceholder = "Password";
            this.regPasswordInput.UseSystemPasswordChar = true;
            this.regPasswordInput.WordWrap = true;
            // 
            // regNumberInput
            // 
            this.regNumberInput.AcceptsReturn = false;
            this.regNumberInput.AcceptsTab = false;
            this.regNumberInput.AnimationSpeed = 200;
            this.regNumberInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.regNumberInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.regNumberInput.AutoSizeHeight = true;
            this.regNumberInput.BackColor = System.Drawing.Color.Transparent;
            this.regNumberInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("regNumberInput.BackgroundImage")));
            this.regNumberInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.regNumberInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.regNumberInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.regNumberInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.regNumberInput.BorderRadius = 20;
            this.regNumberInput.BorderThickness = 1;
            this.regNumberInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.regNumberInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.regNumberInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.regNumberInput.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.regNumberInput.DefaultText = "";
            this.regNumberInput.FillColor = System.Drawing.Color.White;
            this.regNumberInput.ForeColor = System.Drawing.Color.Black;
            this.regNumberInput.HideSelection = true;
            this.regNumberInput.IconLeft = null;
            this.regNumberInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.regNumberInput.IconPadding = 10;
            this.regNumberInput.IconRight = null;
            this.regNumberInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.regNumberInput.Lines = new string[0];
            this.regNumberInput.Location = new System.Drawing.Point(46, 326);
            this.regNumberInput.MaxLength = 32767;
            this.regNumberInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.regNumberInput.Modified = false;
            this.regNumberInput.Multiline = false;
            this.regNumberInput.Name = "regNumberInput";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regNumberInput.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.regNumberInput.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regNumberInput.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regNumberInput.OnIdleState = stateProperties16;
            this.regNumberInput.Padding = new System.Windows.Forms.Padding(3);
            this.regNumberInput.PasswordChar = '\0';
            this.regNumberInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.regNumberInput.PlaceholderText = "Number";
            this.regNumberInput.ReadOnly = false;
            this.regNumberInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.regNumberInput.SelectedText = "";
            this.regNumberInput.SelectionLength = 0;
            this.regNumberInput.SelectionStart = 0;
            this.regNumberInput.ShortcutsEnabled = true;
            this.regNumberInput.Size = new System.Drawing.Size(386, 45);
            this.regNumberInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.regNumberInput.TabIndex = 24;
            this.regNumberInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.regNumberInput.TextMarginBottom = 0;
            this.regNumberInput.TextMarginLeft = 3;
            this.regNumberInput.TextMarginTop = 1;
            this.regNumberInput.TextPlaceholder = "Number";
            this.regNumberInput.UseSystemPasswordChar = false;
            this.regNumberInput.WordWrap = true;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.White;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.Black;
            this.label2.Location = new System.Drawing.Point(94, 573);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(190, 16);
            this.label2.TabIndex = 23;
            this.label2.Text = "By signing up you agree to our ";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.White;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 19.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.Black;
            this.label7.Location = new System.Drawing.Point(39, 30);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(140, 38);
            this.label7.TabIndex = 22;
            this.label7.Text = "Sign Up";
            // 
            // regCloseBtn
            // 
            this.regCloseBtn.AllowAnimations = true;
            this.regCloseBtn.AllowBorderColorChanges = true;
            this.regCloseBtn.AllowDefaults = true;
            this.regCloseBtn.AllowMouseEffects = true;
            this.regCloseBtn.AnimationSpeed = 200;
            this.regCloseBtn.AutoSizeCaptions = true;
            this.regCloseBtn.BackColor = System.Drawing.Color.Transparent;
            this.regCloseBtn.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(233)))), ((int)(((byte)(233)))), ((int)(((byte)(233)))));
            this.regCloseBtn.BackHoverColor = System.Drawing.Color.LightGray;
            this.regCloseBtn.BackPressedColor = System.Drawing.Color.Silver;
            this.regCloseBtn.BorderColor = System.Drawing.Color.LightGray;
            this.regCloseBtn.BorderHoverColor = System.Drawing.Color.DarkGray;
            this.regCloseBtn.BorderPressedColor = System.Drawing.Color.DarkGray;
            this.regCloseBtn.BorderRadius = 25;
            this.regCloseBtn.BorderStyle = Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderStyles.Solid;
            this.regCloseBtn.BorderThickness = 1;
            this.regCloseBtn.CaptionType = Bunifu.UI.WinForms.BunifuFormCaptionButton.CaptionTypes.Close;
            this.regCloseBtn.ColorContrastOnClick = 30;
            this.regCloseBtn.ColorContrastOnHover = 30;
            this.regCloseBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.regCloseBtn.CustomizableEdges = borderEdges4;
            this.regCloseBtn.DefaultBorderColor = System.Drawing.Color.Silver;
            this.regCloseBtn.DefaultColor = System.Drawing.Color.Gainsboro;
            this.regCloseBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.regCloseBtn.IconColor = System.Drawing.Color.Black;
            this.regCloseBtn.IconHoverColor = System.Drawing.Color.Black;
            this.regCloseBtn.IconPressedColor = System.Drawing.Color.Black;
            this.regCloseBtn.Image = ((System.Drawing.Image)(resources.GetObject("regCloseBtn.Image")));
            this.regCloseBtn.ImageMargin = new System.Windows.Forms.Padding(1, 1, 0, 0);
            this.regCloseBtn.ImageSize = new System.Drawing.Size(20, 20);
            this.regCloseBtn.Location = new System.Drawing.Point(430, 10);
            this.regCloseBtn.Name = "regCloseBtn";
            this.regCloseBtn.ShowBorders = true;
            this.regCloseBtn.Size = new System.Drawing.Size(36, 39);
            this.regCloseBtn.TabIndex = 21;
            this.regCloseBtn.Click += new System.EventHandler(this.regCloseBtn_Click);
            // 
            // regAgeInput
            // 
            this.regAgeInput.AcceptsReturn = false;
            this.regAgeInput.AcceptsTab = false;
            this.regAgeInput.AnimationSpeed = 200;
            this.regAgeInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.regAgeInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.regAgeInput.AutoSizeHeight = true;
            this.regAgeInput.BackColor = System.Drawing.Color.Transparent;
            this.regAgeInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("regAgeInput.BackgroundImage")));
            this.regAgeInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.regAgeInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.regAgeInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.regAgeInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.regAgeInput.BorderRadius = 20;
            this.regAgeInput.BorderThickness = 1;
            this.regAgeInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.regAgeInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.regAgeInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.regAgeInput.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.regAgeInput.DefaultText = "";
            this.regAgeInput.FillColor = System.Drawing.Color.White;
            this.regAgeInput.ForeColor = System.Drawing.Color.Black;
            this.regAgeInput.HideSelection = true;
            this.regAgeInput.IconLeft = null;
            this.regAgeInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.regAgeInput.IconPadding = 10;
            this.regAgeInput.IconRight = null;
            this.regAgeInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.regAgeInput.Lines = new string[0];
            this.regAgeInput.Location = new System.Drawing.Point(46, 280);
            this.regAgeInput.MaxLength = 32767;
            this.regAgeInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.regAgeInput.Modified = false;
            this.regAgeInput.Multiline = false;
            this.regAgeInput.Name = "regAgeInput";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regAgeInput.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.regAgeInput.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regAgeInput.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regAgeInput.OnIdleState = stateProperties20;
            this.regAgeInput.Padding = new System.Windows.Forms.Padding(3);
            this.regAgeInput.PasswordChar = '\0';
            this.regAgeInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.regAgeInput.PlaceholderText = "Age";
            this.regAgeInput.ReadOnly = false;
            this.regAgeInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.regAgeInput.SelectedText = "";
            this.regAgeInput.SelectionLength = 0;
            this.regAgeInput.SelectionStart = 0;
            this.regAgeInput.ShortcutsEnabled = true;
            this.regAgeInput.Size = new System.Drawing.Size(386, 45);
            this.regAgeInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.regAgeInput.TabIndex = 19;
            this.regAgeInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.regAgeInput.TextMarginBottom = 0;
            this.regAgeInput.TextMarginLeft = 3;
            this.regAgeInput.TextMarginTop = 1;
            this.regAgeInput.TextPlaceholder = "Age";
            this.regAgeInput.UseSystemPasswordChar = false;
            this.regAgeInput.WordWrap = true;
            // 
            // regNameInput
            // 
            this.regNameInput.AcceptsReturn = false;
            this.regNameInput.AcceptsTab = false;
            this.regNameInput.AnimationSpeed = 200;
            this.regNameInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.regNameInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.regNameInput.AutoSizeHeight = true;
            this.regNameInput.BackColor = System.Drawing.Color.Transparent;
            this.regNameInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("regNameInput.BackgroundImage")));
            this.regNameInput.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.regNameInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.regNameInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.regNameInput.BorderColorIdle = System.Drawing.Color.Silver;
            this.regNameInput.BorderRadius = 20;
            this.regNameInput.BorderThickness = 1;
            this.regNameInput.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.regNameInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.regNameInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.regNameInput.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.regNameInput.DefaultText = "";
            this.regNameInput.FillColor = System.Drawing.Color.White;
            this.regNameInput.ForeColor = System.Drawing.Color.Black;
            this.regNameInput.HideSelection = true;
            this.regNameInput.IconLeft = null;
            this.regNameInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.regNameInput.IconPadding = 10;
            this.regNameInput.IconRight = null;
            this.regNameInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.regNameInput.Lines = new string[0];
            this.regNameInput.Location = new System.Drawing.Point(46, 234);
            this.regNameInput.MaxLength = 32767;
            this.regNameInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.regNameInput.Modified = false;
            this.regNameInput.Multiline = false;
            this.regNameInput.Name = "regNameInput";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regNameInput.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.regNameInput.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regNameInput.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.regNameInput.OnIdleState = stateProperties24;
            this.regNameInput.Padding = new System.Windows.Forms.Padding(3);
            this.regNameInput.PasswordChar = '\0';
            this.regNameInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.regNameInput.PlaceholderText = "Name";
            this.regNameInput.ReadOnly = false;
            this.regNameInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.regNameInput.SelectedText = "";
            this.regNameInput.SelectionLength = 0;
            this.regNameInput.SelectionStart = 0;
            this.regNameInput.ShortcutsEnabled = true;
            this.regNameInput.Size = new System.Drawing.Size(386, 45);
            this.regNameInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.regNameInput.TabIndex = 18;
            this.regNameInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.regNameInput.TextMarginBottom = 0;
            this.regNameInput.TextMarginLeft = 3;
            this.regNameInput.TextMarginTop = 1;
            this.regNameInput.TextPlaceholder = "Name";
            this.regNameInput.UseSystemPasswordChar = false;
            this.regNameInput.WordWrap = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.White;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Black;
            this.label1.Location = new System.Drawing.Point(260, 149);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(162, 16);
            this.label1.TabIndex = 15;
            this.label1.Text = "Already have an account?";
            // 
            // LoginBtnLabel
            // 
            this.LoginBtnLabel.AutoSize = true;
            this.LoginBtnLabel.BackColor = System.Drawing.Color.White;
            this.LoginBtnLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LoginBtnLabel.ForeColor = System.Drawing.SystemColors.ControlText;
            this.LoginBtnLabel.LinkColor = System.Drawing.Color.BlueViolet;
            this.LoginBtnLabel.Location = new System.Drawing.Point(319, 167);
            this.LoginBtnLabel.Name = "LoginBtnLabel";
            this.LoginBtnLabel.Size = new System.Drawing.Size(40, 16);
            this.LoginBtnLabel.TabIndex = 14;
            this.LoginBtnLabel.TabStop = true;
            this.LoginBtnLabel.Text = "Login";
            this.LoginBtnLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.LoginBtnLabel_LinkClicked);
            // 
            // RegisterBtn
            // 
            this.RegisterBtn.AllowAnimations = true;
            this.RegisterBtn.AllowMouseEffects = true;
            this.RegisterBtn.AllowToggling = false;
            this.RegisterBtn.AnimationSpeed = 200;
            this.RegisterBtn.AutoGenerateColors = false;
            this.RegisterBtn.AutoRoundBorders = false;
            this.RegisterBtn.AutoSizeLeftIcon = true;
            this.RegisterBtn.AutoSizeRightIcon = true;
            this.RegisterBtn.BackColor = System.Drawing.Color.Transparent;
            this.RegisterBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.RegisterBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RegisterBtn.BackgroundImage")));
            this.RegisterBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.RegisterBtn.ButtonText = "Register";
            this.RegisterBtn.ButtonTextMarginLeft = 0;
            this.RegisterBtn.ColorContrastOnClick = 45;
            this.RegisterBtn.ColorContrastOnHover = 45;
            this.RegisterBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.RegisterBtn.CustomizableEdges = borderEdges5;
            this.RegisterBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.RegisterBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegisterBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RegisterBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RegisterBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.RegisterBtn.Font = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RegisterBtn.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.RegisterBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.RegisterBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.RegisterBtn.IconMarginLeft = 11;
            this.RegisterBtn.IconPadding = 10;
            this.RegisterBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.RegisterBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.RegisterBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.RegisterBtn.IconSize = 25;
            this.RegisterBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.RegisterBtn.IdleBorderRadius = 35;
            this.RegisterBtn.IdleBorderThickness = 1;
            this.RegisterBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.RegisterBtn.IdleIconLeftImage = null;
            this.RegisterBtn.IdleIconRightImage = null;
            this.RegisterBtn.IndicateFocus = false;
            this.RegisterBtn.Location = new System.Drawing.Point(80, 517);
            this.RegisterBtn.Name = "RegisterBtn";
            this.RegisterBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegisterBtn.OnDisabledState.BorderRadius = 35;
            this.RegisterBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.RegisterBtn.OnDisabledState.BorderThickness = 1;
            this.RegisterBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RegisterBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RegisterBtn.OnDisabledState.IconLeftImage = null;
            this.RegisterBtn.OnDisabledState.IconRightImage = null;
            this.RegisterBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RegisterBtn.onHoverState.BorderRadius = 35;
            this.RegisterBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.RegisterBtn.onHoverState.BorderThickness = 1;
            this.RegisterBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RegisterBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.onHoverState.IconLeftImage = null;
            this.RegisterBtn.onHoverState.IconRightImage = null;
            this.RegisterBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.RegisterBtn.OnIdleState.BorderRadius = 35;
            this.RegisterBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.RegisterBtn.OnIdleState.BorderThickness = 1;
            this.RegisterBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.RegisterBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.OnIdleState.IconLeftImage = null;
            this.RegisterBtn.OnIdleState.IconRightImage = null;
            this.RegisterBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RegisterBtn.OnPressedState.BorderRadius = 35;
            this.RegisterBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.RegisterBtn.OnPressedState.BorderThickness = 1;
            this.RegisterBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RegisterBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.OnPressedState.IconLeftImage = null;
            this.RegisterBtn.OnPressedState.IconRightImage = null;
            this.RegisterBtn.Size = new System.Drawing.Size(328, 39);
            this.RegisterBtn.TabIndex = 13;
            this.RegisterBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.RegisterBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.RegisterBtn.TextMarginLeft = 0;
            this.RegisterBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.RegisterBtn.UseDefaultRadiusAndThickness = true;
            this.RegisterBtn.Click += new System.EventHandler(this.RegisterBtn_Click);
            // 
            // bunifuFormCaptionButton2
            // 
            this.bunifuFormCaptionButton2.AllowAnimations = true;
            this.bunifuFormCaptionButton2.AllowBorderColorChanges = true;
            this.bunifuFormCaptionButton2.AllowDefaults = true;
            this.bunifuFormCaptionButton2.AllowMouseEffects = true;
            this.bunifuFormCaptionButton2.AnimationSpeed = 200;
            this.bunifuFormCaptionButton2.AutoSizeCaptions = true;
            this.bunifuFormCaptionButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormCaptionButton2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(233)))), ((int)(((byte)(233)))), ((int)(((byte)(233)))));
            this.bunifuFormCaptionButton2.BackHoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormCaptionButton2.BackPressedColor = System.Drawing.Color.Silver;
            this.bunifuFormCaptionButton2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuFormCaptionButton2.BorderHoverColor = System.Drawing.Color.DarkGray;
            this.bunifuFormCaptionButton2.BorderPressedColor = System.Drawing.Color.DarkGray;
            this.bunifuFormCaptionButton2.BorderRadius = 25;
            this.bunifuFormCaptionButton2.BorderStyle = Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderStyles.Solid;
            this.bunifuFormCaptionButton2.BorderThickness = 1;
            this.bunifuFormCaptionButton2.CaptionType = Bunifu.UI.WinForms.BunifuFormCaptionButton.CaptionTypes.Close;
            this.bunifuFormCaptionButton2.ColorContrastOnClick = 30;
            this.bunifuFormCaptionButton2.ColorContrastOnHover = 30;
            this.bunifuFormCaptionButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuFormCaptionButton2.CustomizableEdges = borderEdges6;
            this.bunifuFormCaptionButton2.DefaultBorderColor = System.Drawing.Color.Silver;
            this.bunifuFormCaptionButton2.DefaultColor = System.Drawing.Color.Gainsboro;
            this.bunifuFormCaptionButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuFormCaptionButton2.IconColor = System.Drawing.Color.Black;
            this.bunifuFormCaptionButton2.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormCaptionButton2.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormCaptionButton2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuFormCaptionButton2.Image")));
            this.bunifuFormCaptionButton2.ImageMargin = new System.Windows.Forms.Padding(1, 1, 0, 0);
            this.bunifuFormCaptionButton2.ImageSize = new System.Drawing.Size(20, 20);
            this.bunifuFormCaptionButton2.Location = new System.Drawing.Point(783, 3);
            this.bunifuFormCaptionButton2.Name = "bunifuFormCaptionButton2";
            this.bunifuFormCaptionButton2.ShowBorders = true;
            this.bunifuFormCaptionButton2.Size = new System.Drawing.Size(34, 30);
            this.bunifuFormCaptionButton2.TabIndex = 3;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.BackgroundImage = global::MovieMunch.Properties.Resources.MovieM_removebg_preview;
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox1.Location = new System.Drawing.Point(38, -39);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(319, 266);
            this.pictureBox1.TabIndex = 43;
            this.pictureBox1.TabStop = false;
            // 
            // label5
            // 
            this.label5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(20)))), ((int)(((byte)(44)))));
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(69, 198);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(300, 103);
            this.label5.TabIndex = 34;
            this.label5.Text = "Book your movie here";
            // 
            // RegisterForm
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(20)))), ((int)(((byte)(44)))));
            this.ClientSize = new System.Drawing.Size(1200, 650);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.signUpContainer);
            this.ForeColor = System.Drawing.Color.White;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "RegisterForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Register Form";
            this.signUpContainer.ResumeLayout(false);
            this.signUpContainer.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel signUpContainer;
        private Bunifu.UI.WinForms.BunifuTextBox regAgeInput;
        private Bunifu.UI.WinForms.BunifuTextBox regNameInput;
        private Label label1;
        private LinkLabel LoginBtnLabel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 RegisterBtn;
        private Bunifu.UI.WinForms.BunifuFormCaptionButton bunifuFormCaptionButton2;
        private Bunifu.UI.WinForms.BunifuFormCaptionButton regCloseBtn;
        private Label label2;
        private Label label7;
        private LinkLabel linkLabel2;
        private LinkLabel linkLabel1;
        private Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox regConfirmPasswordInput;
        private Bunifu.UI.WinForms.BunifuTextBox regEmailInput;
        private Bunifu.UI.WinForms.BunifuTextBox regPasswordInput;
        private Bunifu.UI.WinForms.BunifuTextBox regNumberInput;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton24;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Label label4;
        private PictureBox pictureBox1;
        private Label label5;
    }
}
