namespace MovieMunch.Admin
{
    partial class MainAdminForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainAdminForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea1 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend1 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series1 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series2 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series3 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series4 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Title title1 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.Title title2 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.Title title3 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.Title title4 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.Title title5 = new System.Windows.Forms.DataVisualization.Charting.Title();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.moviesToShowBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.filmsInCinemaBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.comingSoonBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.foodsBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.homeBtn = new FontAwesome.Sharp.IconButton();
            this.chart1 = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.EmployeeListBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            ((System.ComponentModel.ISupportInitialize)(this.chart1)).BeginInit();
            this.SuspendLayout();
            // 
            // moviesToShowBtn
            // 
            this.moviesToShowBtn.AllowAnimations = true;
            this.moviesToShowBtn.AllowMouseEffects = true;
            this.moviesToShowBtn.AllowToggling = false;
            this.moviesToShowBtn.AnimationSpeed = 200;
            this.moviesToShowBtn.AutoGenerateColors = false;
            this.moviesToShowBtn.AutoRoundBorders = false;
            this.moviesToShowBtn.AutoSizeLeftIcon = true;
            this.moviesToShowBtn.AutoSizeRightIcon = true;
            this.moviesToShowBtn.BackColor = System.Drawing.Color.Transparent;
            this.moviesToShowBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.moviesToShowBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("moviesToShowBtn.BackgroundImage")));
            this.moviesToShowBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.moviesToShowBtn.ButtonText = "Showing";
            this.moviesToShowBtn.ButtonTextMarginLeft = 0;
            this.moviesToShowBtn.ColorContrastOnClick = 45;
            this.moviesToShowBtn.ColorContrastOnHover = 45;
            this.moviesToShowBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.moviesToShowBtn.CustomizableEdges = borderEdges1;
            this.moviesToShowBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.moviesToShowBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.moviesToShowBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.moviesToShowBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.moviesToShowBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.moviesToShowBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.moviesToShowBtn.ForeColor = System.Drawing.Color.White;
            this.moviesToShowBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.moviesToShowBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.moviesToShowBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.moviesToShowBtn.IconMarginLeft = 11;
            this.moviesToShowBtn.IconPadding = 10;
            this.moviesToShowBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.moviesToShowBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.moviesToShowBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.moviesToShowBtn.IconSize = 25;
            this.moviesToShowBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.moviesToShowBtn.IdleBorderRadius = 1;
            this.moviesToShowBtn.IdleBorderThickness = 1;
            this.moviesToShowBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.moviesToShowBtn.IdleIconLeftImage = null;
            this.moviesToShowBtn.IdleIconRightImage = null;
            this.moviesToShowBtn.IndicateFocus = false;
            this.moviesToShowBtn.Location = new System.Drawing.Point(80, 89);
            this.moviesToShowBtn.Name = "moviesToShowBtn";
            this.moviesToShowBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.moviesToShowBtn.OnDisabledState.BorderRadius = 1;
            this.moviesToShowBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.moviesToShowBtn.OnDisabledState.BorderThickness = 1;
            this.moviesToShowBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.moviesToShowBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.moviesToShowBtn.OnDisabledState.IconLeftImage = null;
            this.moviesToShowBtn.OnDisabledState.IconRightImage = null;
            this.moviesToShowBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.moviesToShowBtn.onHoverState.BorderRadius = 1;
            this.moviesToShowBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.moviesToShowBtn.onHoverState.BorderThickness = 1;
            this.moviesToShowBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.moviesToShowBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.moviesToShowBtn.onHoverState.IconLeftImage = null;
            this.moviesToShowBtn.onHoverState.IconRightImage = null;
            this.moviesToShowBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.moviesToShowBtn.OnIdleState.BorderRadius = 1;
            this.moviesToShowBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.moviesToShowBtn.OnIdleState.BorderThickness = 1;
            this.moviesToShowBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.moviesToShowBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.moviesToShowBtn.OnIdleState.IconLeftImage = null;
            this.moviesToShowBtn.OnIdleState.IconRightImage = null;
            this.moviesToShowBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.moviesToShowBtn.OnPressedState.BorderRadius = 1;
            this.moviesToShowBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.moviesToShowBtn.OnPressedState.BorderThickness = 1;
            this.moviesToShowBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.moviesToShowBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.moviesToShowBtn.OnPressedState.IconLeftImage = null;
            this.moviesToShowBtn.OnPressedState.IconRightImage = null;
            this.moviesToShowBtn.Size = new System.Drawing.Size(150, 39);
            this.moviesToShowBtn.TabIndex = 0;
            this.moviesToShowBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.moviesToShowBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.moviesToShowBtn.TextMarginLeft = 0;
            this.moviesToShowBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.moviesToShowBtn.UseDefaultRadiusAndThickness = true;
            this.moviesToShowBtn.Click += new System.EventHandler(this.moviesToShowBtn_Click);
            // 
            // filmsInCinemaBtn
            // 
            this.filmsInCinemaBtn.AllowAnimations = true;
            this.filmsInCinemaBtn.AllowMouseEffects = true;
            this.filmsInCinemaBtn.AllowToggling = false;
            this.filmsInCinemaBtn.AnimationSpeed = 200;
            this.filmsInCinemaBtn.AutoGenerateColors = false;
            this.filmsInCinemaBtn.AutoRoundBorders = false;
            this.filmsInCinemaBtn.AutoSizeLeftIcon = true;
            this.filmsInCinemaBtn.AutoSizeRightIcon = true;
            this.filmsInCinemaBtn.BackColor = System.Drawing.Color.Transparent;
            this.filmsInCinemaBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.filmsInCinemaBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("filmsInCinemaBtn.BackgroundImage")));
            this.filmsInCinemaBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.filmsInCinemaBtn.ButtonText = "Films In Cinema";
            this.filmsInCinemaBtn.ButtonTextMarginLeft = 0;
            this.filmsInCinemaBtn.ColorContrastOnClick = 45;
            this.filmsInCinemaBtn.ColorContrastOnHover = 45;
            this.filmsInCinemaBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.filmsInCinemaBtn.CustomizableEdges = borderEdges2;
            this.filmsInCinemaBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.filmsInCinemaBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.filmsInCinemaBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.filmsInCinemaBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.filmsInCinemaBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.filmsInCinemaBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.filmsInCinemaBtn.ForeColor = System.Drawing.Color.White;
            this.filmsInCinemaBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.filmsInCinemaBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.filmsInCinemaBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.filmsInCinemaBtn.IconMarginLeft = 11;
            this.filmsInCinemaBtn.IconPadding = 10;
            this.filmsInCinemaBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.filmsInCinemaBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.filmsInCinemaBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.filmsInCinemaBtn.IconSize = 25;
            this.filmsInCinemaBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.filmsInCinemaBtn.IdleBorderRadius = 1;
            this.filmsInCinemaBtn.IdleBorderThickness = 1;
            this.filmsInCinemaBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.filmsInCinemaBtn.IdleIconLeftImage = null;
            this.filmsInCinemaBtn.IdleIconRightImage = null;
            this.filmsInCinemaBtn.IndicateFocus = false;
            this.filmsInCinemaBtn.Location = new System.Drawing.Point(80, 178);
            this.filmsInCinemaBtn.Name = "filmsInCinemaBtn";
            this.filmsInCinemaBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.filmsInCinemaBtn.OnDisabledState.BorderRadius = 1;
            this.filmsInCinemaBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.filmsInCinemaBtn.OnDisabledState.BorderThickness = 1;
            this.filmsInCinemaBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.filmsInCinemaBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.filmsInCinemaBtn.OnDisabledState.IconLeftImage = null;
            this.filmsInCinemaBtn.OnDisabledState.IconRightImage = null;
            this.filmsInCinemaBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.filmsInCinemaBtn.onHoverState.BorderRadius = 1;
            this.filmsInCinemaBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.filmsInCinemaBtn.onHoverState.BorderThickness = 1;
            this.filmsInCinemaBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.filmsInCinemaBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.filmsInCinemaBtn.onHoverState.IconLeftImage = null;
            this.filmsInCinemaBtn.onHoverState.IconRightImage = null;
            this.filmsInCinemaBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.filmsInCinemaBtn.OnIdleState.BorderRadius = 1;
            this.filmsInCinemaBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.filmsInCinemaBtn.OnIdleState.BorderThickness = 1;
            this.filmsInCinemaBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.filmsInCinemaBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.filmsInCinemaBtn.OnIdleState.IconLeftImage = null;
            this.filmsInCinemaBtn.OnIdleState.IconRightImage = null;
            this.filmsInCinemaBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.filmsInCinemaBtn.OnPressedState.BorderRadius = 1;
            this.filmsInCinemaBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.filmsInCinemaBtn.OnPressedState.BorderThickness = 1;
            this.filmsInCinemaBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.filmsInCinemaBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.filmsInCinemaBtn.OnPressedState.IconLeftImage = null;
            this.filmsInCinemaBtn.OnPressedState.IconRightImage = null;
            this.filmsInCinemaBtn.Size = new System.Drawing.Size(150, 39);
            this.filmsInCinemaBtn.TabIndex = 1;
            this.filmsInCinemaBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.filmsInCinemaBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.filmsInCinemaBtn.TextMarginLeft = 0;
            this.filmsInCinemaBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.filmsInCinemaBtn.UseDefaultRadiusAndThickness = true;
            this.filmsInCinemaBtn.Click += new System.EventHandler(this.filmsInCinemaBtn_Click);
            // 
            // comingSoonBtn
            // 
            this.comingSoonBtn.AllowAnimations = true;
            this.comingSoonBtn.AllowMouseEffects = true;
            this.comingSoonBtn.AllowToggling = false;
            this.comingSoonBtn.AnimationSpeed = 200;
            this.comingSoonBtn.AutoGenerateColors = false;
            this.comingSoonBtn.AutoRoundBorders = false;
            this.comingSoonBtn.AutoSizeLeftIcon = true;
            this.comingSoonBtn.AutoSizeRightIcon = true;
            this.comingSoonBtn.BackColor = System.Drawing.Color.Transparent;
            this.comingSoonBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.comingSoonBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("comingSoonBtn.BackgroundImage")));
            this.comingSoonBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.comingSoonBtn.ButtonText = "Coming Soon";
            this.comingSoonBtn.ButtonTextMarginLeft = 0;
            this.comingSoonBtn.ColorContrastOnClick = 45;
            this.comingSoonBtn.ColorContrastOnHover = 45;
            this.comingSoonBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.comingSoonBtn.CustomizableEdges = borderEdges3;
            this.comingSoonBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.comingSoonBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.comingSoonBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.comingSoonBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.comingSoonBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.comingSoonBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.comingSoonBtn.ForeColor = System.Drawing.Color.White;
            this.comingSoonBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.comingSoonBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.comingSoonBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.comingSoonBtn.IconMarginLeft = 11;
            this.comingSoonBtn.IconPadding = 10;
            this.comingSoonBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.comingSoonBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.comingSoonBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.comingSoonBtn.IconSize = 25;
            this.comingSoonBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.comingSoonBtn.IdleBorderRadius = 1;
            this.comingSoonBtn.IdleBorderThickness = 1;
            this.comingSoonBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.comingSoonBtn.IdleIconLeftImage = null;
            this.comingSoonBtn.IdleIconRightImage = null;
            this.comingSoonBtn.IndicateFocus = false;
            this.comingSoonBtn.Location = new System.Drawing.Point(80, 270);
            this.comingSoonBtn.Name = "comingSoonBtn";
            this.comingSoonBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.comingSoonBtn.OnDisabledState.BorderRadius = 1;
            this.comingSoonBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.comingSoonBtn.OnDisabledState.BorderThickness = 1;
            this.comingSoonBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.comingSoonBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.comingSoonBtn.OnDisabledState.IconLeftImage = null;
            this.comingSoonBtn.OnDisabledState.IconRightImage = null;
            this.comingSoonBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.comingSoonBtn.onHoverState.BorderRadius = 1;
            this.comingSoonBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.comingSoonBtn.onHoverState.BorderThickness = 1;
            this.comingSoonBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.comingSoonBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.comingSoonBtn.onHoverState.IconLeftImage = null;
            this.comingSoonBtn.onHoverState.IconRightImage = null;
            this.comingSoonBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.comingSoonBtn.OnIdleState.BorderRadius = 1;
            this.comingSoonBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.comingSoonBtn.OnIdleState.BorderThickness = 1;
            this.comingSoonBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.comingSoonBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.comingSoonBtn.OnIdleState.IconLeftImage = null;
            this.comingSoonBtn.OnIdleState.IconRightImage = null;
            this.comingSoonBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.comingSoonBtn.OnPressedState.BorderRadius = 1;
            this.comingSoonBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.comingSoonBtn.OnPressedState.BorderThickness = 1;
            this.comingSoonBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.comingSoonBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.comingSoonBtn.OnPressedState.IconLeftImage = null;
            this.comingSoonBtn.OnPressedState.IconRightImage = null;
            this.comingSoonBtn.Size = new System.Drawing.Size(150, 39);
            this.comingSoonBtn.TabIndex = 2;
            this.comingSoonBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.comingSoonBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.comingSoonBtn.TextMarginLeft = 0;
            this.comingSoonBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.comingSoonBtn.UseDefaultRadiusAndThickness = true;
            this.comingSoonBtn.Click += new System.EventHandler(this.comingSoonBtn_Click);
            // 
            // foodsBtn
            // 
            this.foodsBtn.AllowAnimations = true;
            this.foodsBtn.AllowMouseEffects = true;
            this.foodsBtn.AllowToggling = false;
            this.foodsBtn.AnimationSpeed = 200;
            this.foodsBtn.AutoGenerateColors = false;
            this.foodsBtn.AutoRoundBorders = false;
            this.foodsBtn.AutoSizeLeftIcon = true;
            this.foodsBtn.AutoSizeRightIcon = true;
            this.foodsBtn.BackColor = System.Drawing.Color.Transparent;
            this.foodsBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.foodsBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("foodsBtn.BackgroundImage")));
            this.foodsBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.foodsBtn.ButtonText = "Foods";
            this.foodsBtn.ButtonTextMarginLeft = 0;
            this.foodsBtn.ColorContrastOnClick = 45;
            this.foodsBtn.ColorContrastOnHover = 45;
            this.foodsBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.foodsBtn.CustomizableEdges = borderEdges4;
            this.foodsBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.foodsBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.foodsBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.foodsBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.foodsBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.foodsBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.foodsBtn.ForeColor = System.Drawing.Color.White;
            this.foodsBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.foodsBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.foodsBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.foodsBtn.IconMarginLeft = 11;
            this.foodsBtn.IconPadding = 10;
            this.foodsBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.foodsBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.foodsBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.foodsBtn.IconSize = 25;
            this.foodsBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.foodsBtn.IdleBorderRadius = 1;
            this.foodsBtn.IdleBorderThickness = 1;
            this.foodsBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.foodsBtn.IdleIconLeftImage = null;
            this.foodsBtn.IdleIconRightImage = null;
            this.foodsBtn.IndicateFocus = false;
            this.foodsBtn.Location = new System.Drawing.Point(80, 364);
            this.foodsBtn.Name = "foodsBtn";
            this.foodsBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.foodsBtn.OnDisabledState.BorderRadius = 1;
            this.foodsBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.foodsBtn.OnDisabledState.BorderThickness = 1;
            this.foodsBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.foodsBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.foodsBtn.OnDisabledState.IconLeftImage = null;
            this.foodsBtn.OnDisabledState.IconRightImage = null;
            this.foodsBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.foodsBtn.onHoverState.BorderRadius = 1;
            this.foodsBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.foodsBtn.onHoverState.BorderThickness = 1;
            this.foodsBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.foodsBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.foodsBtn.onHoverState.IconLeftImage = null;
            this.foodsBtn.onHoverState.IconRightImage = null;
            this.foodsBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.foodsBtn.OnIdleState.BorderRadius = 1;
            this.foodsBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.foodsBtn.OnIdleState.BorderThickness = 1;
            this.foodsBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.foodsBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.foodsBtn.OnIdleState.IconLeftImage = null;
            this.foodsBtn.OnIdleState.IconRightImage = null;
            this.foodsBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.foodsBtn.OnPressedState.BorderRadius = 1;
            this.foodsBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.foodsBtn.OnPressedState.BorderThickness = 1;
            this.foodsBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.foodsBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.foodsBtn.OnPressedState.IconLeftImage = null;
            this.foodsBtn.OnPressedState.IconRightImage = null;
            this.foodsBtn.Size = new System.Drawing.Size(150, 39);
            this.foodsBtn.TabIndex = 3;
            this.foodsBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.foodsBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.foodsBtn.TextMarginLeft = 0;
            this.foodsBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.foodsBtn.UseDefaultRadiusAndThickness = true;
            this.foodsBtn.Click += new System.EventHandler(this.foodsBtn_Click);
            // 
            // homeBtn
            // 
            this.homeBtn.IconChar = FontAwesome.Sharp.IconChar.HomeLg;
            this.homeBtn.IconColor = System.Drawing.Color.Black;
            this.homeBtn.IconFont = FontAwesome.Sharp.IconFont.Auto;
            this.homeBtn.Location = new System.Drawing.Point(1113, 12);
            this.homeBtn.Name = "homeBtn";
            this.homeBtn.Size = new System.Drawing.Size(75, 57);
            this.homeBtn.TabIndex = 4;
            this.homeBtn.UseVisualStyleBackColor = true;
            this.homeBtn.Click += new System.EventHandler(this.homeBtn_Click);
            // 
            // chart1
            // 
            chartArea1.Name = "Total User";
            this.chart1.ChartAreas.Add(chartArea1);
            legend1.Name = "Legend1";
            this.chart1.Legends.Add(legend1);
            this.chart1.Location = new System.Drawing.Point(325, 133);
            this.chart1.Name = "chart1";
            this.chart1.Palette = System.Windows.Forms.DataVisualization.Charting.ChartColorPalette.Excel;
            series1.ChartArea = "Total User";
            series1.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.StackedColumn;
            series1.Legend = "Legend1";
            series1.Name = "Total User";
            series2.ChartArea = "Total User";
            series2.Legend = "Legend1";
            series2.Name = "Series2";
            series3.ChartArea = "Total User";
            series3.Legend = "Legend1";
            series3.Name = "Series3";
            series4.ChartArea = "Total User";
            series4.Legend = "Legend1";
            series4.Name = "Series4";
            this.chart1.Series.Add(series1);
            this.chart1.Series.Add(series2);
            this.chart1.Series.Add(series3);
            this.chart1.Series.Add(series4);
            this.chart1.Size = new System.Drawing.Size(758, 457);
            this.chart1.TabIndex = 7;
            this.chart1.Text = "Report";
            title1.Name = "Total User";
            title2.Name = "Title1";
            title3.Name = "Title2";
            title4.Name = "Title3";
            title5.Name = "Title4";
            this.chart1.Titles.Add(title1);
            this.chart1.Titles.Add(title2);
            this.chart1.Titles.Add(title3);
            this.chart1.Titles.Add(title4);
            this.chart1.Titles.Add(title5);
            // 
            // EmployeeListBtn
            // 
            this.EmployeeListBtn.AllowAnimations = true;
            this.EmployeeListBtn.AllowMouseEffects = true;
            this.EmployeeListBtn.AllowToggling = false;
            this.EmployeeListBtn.AnimationSpeed = 200;
            this.EmployeeListBtn.AutoGenerateColors = false;
            this.EmployeeListBtn.AutoRoundBorders = false;
            this.EmployeeListBtn.AutoSizeLeftIcon = true;
            this.EmployeeListBtn.AutoSizeRightIcon = true;
            this.EmployeeListBtn.BackColor = System.Drawing.Color.Transparent;
            this.EmployeeListBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.EmployeeListBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EmployeeListBtn.BackgroundImage")));
            this.EmployeeListBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.EmployeeListBtn.ButtonText = "Employee";
            this.EmployeeListBtn.ButtonTextMarginLeft = 0;
            this.EmployeeListBtn.ColorContrastOnClick = 45;
            this.EmployeeListBtn.ColorContrastOnHover = 45;
            this.EmployeeListBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.EmployeeListBtn.CustomizableEdges = borderEdges5;
            this.EmployeeListBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.EmployeeListBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.EmployeeListBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EmployeeListBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.EmployeeListBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.EmployeeListBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.EmployeeListBtn.ForeColor = System.Drawing.Color.White;
            this.EmployeeListBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.EmployeeListBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.EmployeeListBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.EmployeeListBtn.IconMarginLeft = 11;
            this.EmployeeListBtn.IconPadding = 10;
            this.EmployeeListBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.EmployeeListBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.EmployeeListBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.EmployeeListBtn.IconSize = 25;
            this.EmployeeListBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.EmployeeListBtn.IdleBorderRadius = 1;
            this.EmployeeListBtn.IdleBorderThickness = 1;
            this.EmployeeListBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.EmployeeListBtn.IdleIconLeftImage = null;
            this.EmployeeListBtn.IdleIconRightImage = null;
            this.EmployeeListBtn.IndicateFocus = false;
            this.EmployeeListBtn.Location = new System.Drawing.Point(80, 458);
            this.EmployeeListBtn.Name = "EmployeeListBtn";
            this.EmployeeListBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.EmployeeListBtn.OnDisabledState.BorderRadius = 1;
            this.EmployeeListBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.EmployeeListBtn.OnDisabledState.BorderThickness = 1;
            this.EmployeeListBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EmployeeListBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.EmployeeListBtn.OnDisabledState.IconLeftImage = null;
            this.EmployeeListBtn.OnDisabledState.IconRightImage = null;
            this.EmployeeListBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.EmployeeListBtn.onHoverState.BorderRadius = 1;
            this.EmployeeListBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.EmployeeListBtn.onHoverState.BorderThickness = 1;
            this.EmployeeListBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.EmployeeListBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.EmployeeListBtn.onHoverState.IconLeftImage = null;
            this.EmployeeListBtn.onHoverState.IconRightImage = null;
            this.EmployeeListBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.EmployeeListBtn.OnIdleState.BorderRadius = 1;
            this.EmployeeListBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.EmployeeListBtn.OnIdleState.BorderThickness = 1;
            this.EmployeeListBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.EmployeeListBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.EmployeeListBtn.OnIdleState.IconLeftImage = null;
            this.EmployeeListBtn.OnIdleState.IconRightImage = null;
            this.EmployeeListBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.EmployeeListBtn.OnPressedState.BorderRadius = 1;
            this.EmployeeListBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.EmployeeListBtn.OnPressedState.BorderThickness = 1;
            this.EmployeeListBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.EmployeeListBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.EmployeeListBtn.OnPressedState.IconLeftImage = null;
            this.EmployeeListBtn.OnPressedState.IconRightImage = null;
            this.EmployeeListBtn.Size = new System.Drawing.Size(150, 39);
            this.EmployeeListBtn.TabIndex = 8;
            this.EmployeeListBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.EmployeeListBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.EmployeeListBtn.TextMarginLeft = 0;
            this.EmployeeListBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.EmployeeListBtn.UseDefaultRadiusAndThickness = true;
            this.EmployeeListBtn.Click += new System.EventHandler(this.EmployeeListBtn_Click);
            // 
            // MainAdminForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1200, 650);
            this.Controls.Add(this.EmployeeListBtn);
            this.Controls.Add(this.chart1);
            this.Controls.Add(this.homeBtn);
            this.Controls.Add(this.foodsBtn);
            this.Controls.Add(this.comingSoonBtn);
            this.Controls.Add(this.filmsInCinemaBtn);
            this.Controls.Add(this.moviesToShowBtn);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "MainAdminForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "MainAdminForm";
            ((System.ComponentModel.ISupportInitialize)(this.chart1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 moviesToShowBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 filmsInCinemaBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 comingSoonBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 foodsBtn;
        private FontAwesome.Sharp.IconButton homeBtn;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 EmployeeListBtn;
    }
}